"""core schema: users, cards, categories, transactions and catalogs

Revision ID: e1373aa38dd7
Revises: 
Create Date: 2026-01-01 23:02:13.793923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1373aa38dd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id_bank', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_bank'),
    sa.UniqueConstraint('name')
    )
    op.create_table('card_types',
    sa.Column('id_card_type', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_card_type'),
    sa.UniqueConstraint('type')
    )
    op.create_table('currency',
    sa.Column('id_currency', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_currency'),
    sa.UniqueConstraint('code')
    )
    op.create_table('transaction_type',
    sa.Column('id_transaction_type', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_transaction_type'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cards',
    sa.Column('id_card', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_bank', sa.UUID(), nullable=False),
    sa.Column('id_currency', sa.UUID(), nullable=False),
    sa.Column('id_card_type', sa.UUID(), nullable=False),
    sa.Column('last_digits', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_used', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cut_day', sa.Integer(), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_bank'], ['banks.id_bank'], ),
    sa.ForeignKeyConstraint(['id_card_type'], ['card_types.id_card_type'], ),
    sa.ForeignKeyConstraint(['id_currency'], ['currency.id_currency'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_card')
    )
    op.create_table('categories',
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id_category'], ),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('transactions',
    sa.Column('id_transaction', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_card', sa.UUID(), nullable=False),
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('id_transaction_type', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('related_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_card'], ['cards.id_card'], ),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ),
    sa.ForeignKeyConstraint(['id_transaction_type'], ['transaction_type.id_transaction_type'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('categories')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('transaction_type')
    op.drop_table('currency')
    op.drop_table('card_types')
    op.drop_table('banks')
    # ### end Alembic commands ###
